### ISSUE TITLE
No programs for Siemens WD14U592

### ISSUE THREAD

**Issue by Krocko** [ekutner/home-connect-hass#1]
Hi. I am currently testing your integration. 

For my Siemens WashDryer there are no options for the program input.select. 
The Remaining Program Time is also not available. 

![EA24D9A8-CCFB-4CA5-90B9-8DB73C01677D](https://user-images.githubusercontent.com/29394115/153548890-562a1271-e81b-406a-b180-519b2463142c.jpeg)

Could the following issue also the reason here?
https://github.com/DavidMStraub/homeassistant-homeconnect/issues/119

**Comment by Krocko** [comment]
Sure.

![image](https://user-images.githubusercontent.com/29394115/153566167-40c0ae8b-2c8c-4490-b3de-9fec1e1b2978.png)
![image](https://user-images.githubusercontent.com/29394115/153566181-bb375fd9-895b-4069-a35b-cbae17122584.png)
![image](https://user-images.githubusercontent.com/29394115/153566190-6d583476-736b-44cc-9274-a2dc598c1b8d.png)
![image](https://user-images.githubusercontent.com/29394115/153566201-c91543e4-d20f-4943-a809-d6560ed91b20.png)

**Comment by ekutner** [comment]
It seems that the appliance was running a program at the time. Program, and program-option selection is disabled when a program is active because these settings can't be changed until the program completes. There was a bug that the program-options weren't disabled, which should be fixed now.
There was also a bug that affected status updates, so if you didn't see the status change, that should be resolved now as well.

While reviewing this I noticed that your language was German. Complete language support is still TBD but you can now add a *language* setting to the home_connect_alt entry in configuration.yaml with your locale and content that comes from Home Connect should automatically be translated. Let me know if that works. Your setting should look something like this:
```
home_connect_alt:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
  language: de-DE
```

**Comment by Krocko** [comment]
Thank you. Some parts are now in German.

The status updates don't working anymore on both devices. Also the refresh button does nothing.
