### ISSUE TITLE
how to use entity states in yaml-templates?

### ISSUE THREAD

**Issue by ChristophCaina** [ekutner/home-connect-hass#120]
## Describe the bug
The API returns the state of a sensor as EnumType (?) like this:

sensor.siemens_ti****_******de_selected_program
--> `ConsumerProducts.CoffeeMaker.Program.Beverage.Coffee`

while using the sensor within a Dashboard, everything is displayed as expected:
![grafik](https://user-images.githubusercontent.com/26391061/196865170-f0db9477-25fc-4b28-b51e-1c544fecc327.png)

But using the sensor within a template - or for example for a notification, it does not "translate" the sensor state.
![grafik](https://user-images.githubusercontent.com/26391061/196865307-2437280d-57b0-4d50-b7b7-3dd9447c17af.png)

How can I get the translated information within a template?

**Comment by ekutner** [comment]
You can set "sensor_value_translation: server" in your configuration (see the README) but that is not a good practice.
Templates are a kind of programing and when you write a program you don't want to use "display values" because those might change (which they do) and break your code. The ENUM values are there exactly for that reason, they are constant values that can will remain unchanged even if the display value is changed or you use a different language.
