### ISSUE TITLE
Possible to reset the running program on a Dishwasher

### ISSUE THREAD

**Issue by woopstar** [ekutner/home-connect-hass#122]
**Describe the solution you'd like**
It would be beneficial if you can reset the current program started. Currently, you can only power off the appliance, but you cannot reset the chosen program and change it to something else from automations.

**Comment by ChristophCaina** [comment]
I wonder if this is possible with the regular HomeConnect App ... and I have some doubts... 
Since the integration does only expose the API options to HomeAssistant, I don't think that this is possible.

For example - on my coffeemaker, many options become unavailable as long an action is running.
With this in mind, the API seems to block interruption by the user - probably, to prevent the device to go into an unconditioned situation

**Comment by ekutner** [comment]
It depends on the appliance. The API does allow pausing, resuming and stopping running programs and the integration supports that when it is available. However, that functionality is not available for most appliances. Interestingly, there was a brief period of time a few months ago, where it was available for a lot more appliances and then they removed it, I don't know why and they do not respond to support requests so it's not possible to get any answers from them.
