### ISSUE TITLE
Sensor Oven doesn't update during program running

### ISSUE THREAD

**Issue by zufivan** [ekutner/home-connect-hass#149]
Hi ekutner, 
today the oven (BOSCH-HNG6764S6)  start program at 8:55 (Roastbeff-al sangue) but the sensors for the oven weren't updating (example: active program, elapsed program time, ecc)
At 9:28 I pressed the integration button  "refresh" and the sensors updated again.
See in attacched  debug log.

Often the sensor "sensor.bosch_hng6764s6_68a40e03aeeb_cooking_oven_status_currentcavitytemperature" doesn't update for long time.

[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/10402654/home-assistant.log)

Version 0.5.9

Many thanks Ivan

**Comment by ekutner** [comment]
According to the log the program was started at 08:54:11 and the active program was correctly updated at that time, along with 4 additional program options. After that the ElapsedProgramTime and ProgramProgress sensors were continuously updated based on events received from HC. The CurrentActivityTemperture is not being updated because HC doesn't send update events for that sensor. 
Note that the integration is "cloud push" type, that means that it updates based on events it receives from the cloud service (Home Connect). If HC fails to send update events then the values will not be updated. When you press the refresh button you force an active pull of data and that's why you saw it update at that time. Bottom line is that this is an problem with HC, not the integration.

**Comment by zufivan** [comment]
Hi @ekutner, thanks for the reply, unfortunately the sensor on home hassistant was not updated before I pressed the "refresh" button. maybe the problem is on home assistant? Following print screnn about sensor in HA:

**(sensor.bosch_hng6764s6_68a40e03aeeb_bsh_common_option_elapsedprogramtime)**
![image](https://user-images.githubusercontent.com/47624226/212372560-82d94a6e-e95e-495c-bd19-7e7ac5735d2a.png)

**(sensor.bosch_hng6764s6_68a40e03aeeb_active_program)**
![image](https://user-images.githubusercontent.com/47624226/212372918-fba38f5f-1e5c-4de6-8222-3cb7c6938b86.png)

**at the same time the dishwasher was working and all the sensors were working perfectly,** (sensor.bosch_sma88td16e_68a40e12153d_bsh_common_option_programprogress):
![image](https://user-images.githubusercontent.com/47624226/212374003-d879e447-0c37-47bd-b5e4-d483e3d13be2.png)

thanks a lot for your support

**Comment by ekutner** [comment]
I'm not sure what to make of it. Can you reproduce this issue? Does it always happen for this appliance?
Please add the entry `log_mode: 7` to the home_connect_alt section in configuration.yaml
Then, wait until this issue happens again. When you see it press the "Home Connect Debug" button BEFORE you press the "Refresh" button. Then upload the log again.

**Comment by zufivan** [comment]
Hi @ekutner, for a week the issue did not happen. I was unable to reproduce the problem. So the integration works perfectly 👍
Just last think, I understood that the "CurrentActivityTemperture" is not being updated because HC doesn't send update events, do you think it's possible  to have a service to be called by script on HA to update the sensor when the hoven is running?
thanks Ivan

**Comment by ekutner** [comment]
Happy to hear that, although I still don't really understand why it didn't work when it didn't.
Re. the service suggestion, it can be done but I don't think it's not a good idea, because it will dramatically increase the chance of hitting the (unreasonably low) daily API call limit.

**Comment by zufivan** [comment]
Hi @ekutner  thank you very much, i understand fo the service suggestion. 
Regards Ivan
