### ISSUE TITLE
Error on program selection. Balay dishwasher. 

### ISSUE THREAD

**Issue by maaper** [ekutner/home-connect-hass#152]
I’m running the last version of the integration. 
I made a program that should turn on the dishwasher, select the appropriate program and start it. 
I found the following error on running the automation. Only when trying to run the step of program selection. 

![7A92774F-7188-4304-9E2B-6FA18D3E254F](https://user-images.githubusercontent.com/56989894/214764338-4036c63c-3cbc-419b-953d-dde0c68d42e0.jpeg)

The same integrations runs ok with the official home connect integration, but I like the way that this unofficial integration represent the entities. Any idea on how to solve the error?

**Comment by ekutner** [comment]
You should use the select_program service instead of trying to change the select entity. I never tested it like this and not sure what exactly it does under the hood. That said, the reported error is coming from Home Connect, not from the integration itself, because the appliance is not in the Ready state. This will not work on the built-in integration either while the appliance is in this state.
