### ISSUE TITLE
Since a few hours Status blocked

### ISSUE THREAD

**Issue by henne49** [ekutner/home-connect-hass#173]
## Describe the bug
Since a few hours the integration shows blocked: 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/4662326/221260245-8250f884-6bf5-4319-ac0d-4e6cf2f1bed0.png">

## Version of the custom_component
0.5.10

**Comment by henne49** [comment]
it is working again: 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4662326/221345119-53c2cc5e-4875-44c5-8804-d0fd2162e330.png">

**Comment by henne49** [comment]
that was what I had as well, but gone this morning

**Comment by henne49** [comment]
did nothing, I thought it might be a problem with the API

**Comment by ekutner** [comment]
Read the README

**Comment by ekutner** [comment]
BLOCKED, is always because of rate limits. The mobile app is not using the same API at all and as for the other integration I don't know what you mean by same credentials. The rate limits are counted for each client_id separately. It can happen at night if your appliance is getting disconnected and reconnected to the wifi network a lot, causing the integration to make a lot of calls every time it does that. Search for "blocked" in previous issue and you should see all the possible reasons. For example here: #127

**Comment by Sweti934** [comment]
Hei I had the same issue today. Is there a way to reduce the calls per minute  ?Thanks!

**Comment by Rep-Hueman** [comment]
Fast work around!
If you are blocked....

- Create a new app on Home Connect developers website and link it to HA configuration.yaml with the new Client ID and Client Secret. 
- Remove the integration in HA and add it back immediately. (window will popup where you will be asked to login to to your Home Connect account) 
- Wait a minute and all entities will be back and available!

No reboot is necessary!
