### ISSUE TITLE
Siemens eq.900 - turn on / off gone?

### ISSUE THREAD

**Issue by Symbiot78** [ekutner/home-connect-hass#194]
hi

I have an automation that turns on (and off) my coffee machine in the morning so it's ready when I get up ( most important automation in the world! :) )

Anyway.. it stopped working.
Sat down to investigate... as far as I can tell.. the possibility to turn on my coffee machine is gone from the device. 

No turn on or off option available within the device. 

is this something from the API, or in the integration that has changed?

Please let me know what you need me to provide.. if anything..

**Comment by Symbiot78** [comment]
hm.. maybe the device name/id or option changed. .but found this:

Change Siemens Kaffemaskine - Power State option

will test..

**Comment by Symbiot78** [comment]
Nope - none of the device options work. I cannot find a way to turn on my coffee machine :-(

**Comment by ekutner** [comment]
Follow the instructions for reporting an issue

**Comment by Rep-Hueman** [comment]
i sent a log for this problem in 0.6.1-b3

https://github.com/ekutner/home-connect-hass/issues/185

**Comment by ekutner** [comment]
I assume this is working now

**Comment by metawops** [comment]
I know this is closed already but I wonder how @Symbiot78 ever managed to power on and off the EQ.9 in an automation?
I'm not successful, currently, and because this issue is very closed to my problem I thought I'd add this comment here.

Home Connect alt offers 5 services, 4 deal with programs and the other one allows to "Apply settings".
Is changing the power state from "Standby" to "On" applying a setting? Otherwise I don't know how to automate the power state.
I tried it with this service call ...
```yaml
service: home_connect_alt.apply_setting
data:
  key: BSH.Common.Setting.PowerState
  value: "On"
  device_id: 8de92ed9ecb59bfb1a04458exxxxxxxx
```

... but that didn't work. Neither for the value "on" (all small letters) nor for "Standby"/"standby".

Maybe I'm on a totally wrong path here? 😳

**Comment by ekutner** [comment]
The value has to be one from here: https://api-docs.home-connect.com/settings#power-state

**Comment by metawops** [comment]
Awesome!! Thanks so much! Works like a charm! 😊
