### ISSUE TITLE
Sensors or Select boxes are shoing raw enum values looking something like BSH.Common.Program.XXX 

### ISSUE THREAD

**Issue by ekutner** [ekutner/home-connect-hass#26]
These values are used by the Home connect API and exposed by the integration for scripting and event publishing. The integration is using these values so they match the Home Connect API documentation.
Since these enum values are not very user friendly the integration relies on the Home Assistant translation capabilities to translate them into friendly names in supported languages. All the documented values have already been translated however there seem to be some undocumented values that can only be translated when users report them because until that happens there is no way to know they even exist. In the comments to this issue you can report on untranslated values to be added to the integration. 
Please do NOT share screenshots, only text values of these enum values will be considered.

### Important Note
The Home Assistant translation doesn't seem work for the sensor history display, so please don't report on their existence in there.

**Comment by emufan** [comment]
BSH.Common.EnumType.PowerState.Off
BSH.Common.EnumType.PowerState.On
BSH.Common.EnumType.OperationState.Inactive

And for
Dishcare.Dishwasher.Program.Intensiv70, Dishcare.Dishwasher.Program.Auto2, Dishcare.Dishwasher.Program.Eco50, Dishcare.Dishwasher.Program.NightWash, Dishcare.Dishwasher.Program.Kurz60, Dishcare.Dishwasher.Program.Glas40, Dishcare.Dishwasher.Program.Quick45, Dishcare.Dishwasher.Program.PreRinse, Dishcare.Dishwasher.Program.MachineCare
I don't know yet, if this working by design or should be used/displayed (I would prefer) as Intensiv70, Auto2, Eco50, etc.

**Comment by ekutner** [comment]
@emufan Where exactly do you see those values and and in what language? They are already translated and should appear in their friendly names in English and German. You can see the translation files here: https://github.com/ekutner/home-connect-hass/tree/master/custom_components/home_connect_alt/translations

If you are using a different language you are welcome to contribute a translation to that language.

**Comment by BeerBOFH** [comment]
Seeing the same issue here as emufan on a Washing Machine and using Home Assistant in English.

BSH.Common.EnumType.OperationState.Ready
BSH.Common.EnumType.PowerState.Off
BSH.Common.EnumType.PowerState.On
LaundryCare.Washer.Program.*

If I add "language: en-GB" to configuration.yaml the values appear correctly.

**Comment by ekutner** [comment]
@emufan As I noted. They are in the developer tools by design. These are the values documented in the Home Connect API documentation so they are also used for scripting the integration. Scripts should not depend of translated strings and these values will work regardless of your selected language. 
They show up in the history because of a limitation in the HA translation implementation (at least as far as I can tell). I'm planning to open a feature request to improve this but haven't gotten to it yet.

@BeerBOFH If you see these values in the same place as @emufan  then see the above explanation, otherwise specify where you do see them.

**Comment by emufan** [comment]
> They are in the developer tools by design.

I think you are wrong. As this was/is not the case for other entities **and** after putting now de-DE in yaml, most of them disappeared as well. Afterwards not only the status is shown correctly in entity, it is shown in developer tools and history correctly as well. Not for all items but for most of them.

So this cannot be by design, but different assignments in the integration. Here I'm not the expert, if you hand over different variables for log, recorder and state or whatever is happening compared to the entities which were correct directly from the beginning and those, which are now right with de-DE and which are still not correct.

I will start from scratch and will make a table next days, if I have more time, and provide the findings. Perhaps you can then easier find the different behavior in your codings.

**Comment by emufan** [comment]
O.k. could be the case. I will double-check.

**Comment by emufan** [comment]
O.k. Much better. 😉

I have added three missing EnumTypes per PR.

But I still get not, why it is possible for alarm_control_panel, cover, media-player, weather, etc. entities to display is "correctly" in history. Besides the select boxes, but they of course differ from the other entities.

And what is with the yellow and orange items in the third column. See questions above.

**Comment by ekutner** [comment]
I'm not sure what is your question re. the red and yellow.
However, looking at the table reminded me that setting the language param also translated the entity names, not only the sensor values. So now I think I understand what you asked for in the previous comment. I can add a parameter that will separate the state and the name translation, and makes sense to add it.

**Comment by emufan** [comment]
> So now I think I understand what you asked for in the previous comment. I can add a parameter that will separate the state and the name translation, and makes sense to add it.

Yes, that was what I wanted to suggest.

> I'm not sure what is your question re. the red and yellow.

First the one is Off (and in other case most probably On) and all others are off/on in lowercase. And for me it seems that these are booleans, but in these cases not created as boolean-sensors. But perhaps you drive the type from the API and than it is as it is.

**Comment by ekutner** [comment]
The type is derived automatically from the API. You can tell the type of sensor by looking at the entity ID which starts either with "binary_sensor", for boolean sensors, or with "sensor", for all other types. 
When you see "Off" in a regular sensor, that's because it can have other, non-boolean, values. For example, on my washing machine the level of detergent to use can be High, Medium, Low or Off, indicating the machine should not add detergent automatically.

**Comment by mija87** [comment]
Hi,

If I add sensor_value_translation: server to the config, i get to see this: Invalid config for [home_connect_alt]: [sensor_value_translation] is an invalid option for [home_connect_alt]. Check: home_connect_alt->home_connect_alt->sensor_value_translation. (See /config/configuration.yaml, line 31). 

Someone have an idea about this?

**Comment by alsFC** [comment]
> Hi,
> 
> If I add sensor_value_translation: server to the config, i get to see this: Invalid config for [home_connect_alt]: [sensor_value_translation] is an invalid option for [home_connect_alt]. Check: home_connect_alt->home_connect_alt->sensor_value_translation. (See /config/configuration.yaml, line 31).
> 
> Someone have an idea about this?

same for me
`sensor_value_translation: server` as well as `sensor_value_translation: local` don't work. Rolled back to 1.4.6.

**Comment by alexdelprete** [comment]
I see two sensors (BHS.Common.*) not translated, but they are in the select.en.json translation file.

![image](https://user-images.githubusercontent.com/7027842/173184660-fa4421ae-1e86-40a2-aa83-f20d412b20c9.png)

I have translation set to local and language set to en, I tried using en-GB but it makes no difference.

What am I missing?

**Comment by ekutner** [comment]
@alexdelprete it's a bit confusing but the translation file is not selected by what you configure in the integration configuration but by the language you have configured for the Home Assistant. Is your HA language English?

As a side note, I noticed that the translation you are getting from the server for the Auto2 program is not just "Auto 2" but "Auto 45-65C" so would be great if you can check what are the correct translations for Auto1 and Auto3 as well.

**Comment by alexdelprete** [comment]
> Is your HA language English?

IIRC, HA language is based on the user profile. I can't find a "default language" setting.

> so would be great if you can check what are the correct translations for Auto1 and Auto3 as well

so I switch the program on the dishwasher and report back what's being sent by the server?

**Comment by ekutner** [comment]
I was referring to the language set in the profile.

**Comment by alexdelprete** [comment]
> I was referring to the language set in the profile.

It's english.

**Comment by alexdelprete** [comment]
> would be great if you can check what are the correct translations for Auto1 and Auto3 as well.

I have eight programs, tried them all starting from the first (Auto 35-45°C):

![image](https://user-images.githubusercontent.com/7027842/173203463-f4f140ca-44b5-4140-83b1-e36fc6a86863.png)

**Comment by ekutner** [comment]
> > I was referring to the language set in the profile.
> 
> It's english.
Then I'm not sure what can cause this because it is handled automatically by HA. There are a few things worth trying:
1. Change the HA language to German and see if these values get translated to German.
2. Verify that the translation folder exists on your hard drive and has the same permissions as the other folders. This is unlikely to be the issue but I'm just throwing any idea I have.
3. If they don't get translated then let me know what is the entity IDs of the sensor that shows the untranslated values, just to make sure the translation is in the correct section of the file.

**Comment by emufan** [comment]
@ekutner What happened now with 0.5.0?

I have still `sensor_value_translation: local`but now the entity value is not e.g. BSH.xxx.enum.... anmore, but only the translated value. On UI, but in history and developer tools as well. 

![image](https://user-images.githubusercontent.com/22775515/175034107-730d61d8-8937-4491-bbba-2c675c19e783.png)

![image](https://user-images.githubusercontent.com/22775515/175034127-6463b7e8-1063-445d-b694-249026d44de9.png)

**Comment by ekutner** [comment]
@emufan 
I can't think of any change in that release that would cause a change in this behavior and it's behaving as it should for me. Are you sure you have the sensor value translation set to local?

**Comment by emufan** [comment]
local is working again!

**Comment by robertwigley** [comment]
WASHING MACHINE
sensor.washing_machine_vario_perfect: LaundryCare.Common.EnumType.VarioPerfect.Off
sensor.washing_machine_temperature: LaundryCare.Washer.EnumType.Temperature.GC60
sensor.washing_machine_stains: LaundryCare.Washer.EnumType.Stains.Off
sensor.washing_machine_spin_speed: LaundryCare.Washer.EnumType.SpinSpeed.RPM1600
sensor.washing_machine_selected_program: LaundyCare.Washer.Program.Cotton
sensor.washing_machine_power_state: BSH.Common.EnumType.PowerState.On
sensor.washing_machine_operation_status: BSH.Common.EnumType.OperationState.Ready

**Comment by Avatar1976** [comment]
Hi guys, found another one not displaying correctly this one appears to be ProcessPhase:
LaundryCare.Common.EnumType.ProcessPhase.DetectingLoad

**Comment by iceymanz** [comment]
I wasn't sure if I should create an issue about this but I too have had a spotty result with LaundryCare.Common.EnumType.ProcessPhase.DetectingLoad.

Detectingload was the only processphase that my washing machine would report - and inconsistently - not every load. I haven't seen it since updating from (I believe 0.5.0) to 0.5.5 - even after 3 different cycles with all the debug modes enabled (can provide log somewhere if useful to ekutner at all).

For some background, I have just changed to this washer from an old mechnical dial clunker and I was interested in getting as much info about the stage of the wash as possible to help determine 1) how it dynamically estimates runtime 2) where it adds in additional stages due to 'Foam Detection' - the latter being something that appears only to be available via the [internal API](https://github.com/ekutner/home-connect-hass/issues/91#issuecomment-1209492326)

**Comment by sesthan** [comment]
Hi, seems like there is missmatch between color translation on my Hood and the one used in translation file. My model is DWF97RW61 and I get the following when changeling color from the app and look at the sensor in HASS

App Name		sensor.bosch_X_bsh_common_setting_ambientlightcolor

white (lemon)		White
white (ocher)		Warm white
white (gold) 		Color43
white (apricot)		Color44
red				Color45
orange			Color46
yellow			Color47
green			Color48
blue				Color49
purple			Color50
Cold white		Color51
white			Color52

**Comment by ekutner** [comment]
@sesthan I'm happy to review a PR that sets the correct translation. If you don't know how to do that then please provide a list of the full ENUM value and the translation it should have and I'll add that to the translation files.

**Comment by DjBac** [comment]
COOKTOP
Cooking.Hob.EnumType.PowerLevel.Off
Cooking.Hob.Program.PowerLevelMode
Cooking.Hob.EnumType.ZoneSelector.FrontRight

**Comment by ekutner** [comment]
@DjBac In order to add these value to the translation table I need to know:
1. What entity type they are associated with. You can find that out by  looking at the first part of the entity ID (should be something like, sensor/select/number etc.) 
2. How they are translated in the mobile app (this is optional but preferred if you can find it out).

**Comment by ChristophCaina** [comment]
I also want to join here :)

1. in the description of the site, you are using the information about the language codes:

> language (optional - default = "en") - Indicates the language to use for entity names. The translation is automatically loaded from the Home Connect service and must be one of its [supported languages](https://api-docs.home-connect.com/general?#supported-languages).

The link to the supported languages is showing the language "Primary language tag" like `en`, `de`, and so on - but then, there's the information about the supported language tags - which are `en-EN`, `de-DE` and so on.

First, that should be changed in the readme - because the initial default="en" indicates that this is the language tag -format that you should use during the setup.

And this is how I used the language tag in my setup.
I also had all strange "entity names" in the select boxes (unfortunately, I haven't made a screenshot...)
but due to the length and format, it was nearly impossible to read what the options should be.

With the information I found here, I've changed the language tag to `de-DE` and rebooted homeassistant.
All selections switched to the correct option and format:

![grafik](https://user-images.githubusercontent.com/26391061/196777123-6b679cc1-22c4-4fdd-b4fe-8cdb25cf9016.png)

There's only one sensor left, that is not showing the correct format:

![grafik](https://user-images.githubusercontent.com/26391061/196777247-8fba883e-b799-4077-abce-b8b3ec10c718.png)

I don't know how this does behave when I select one of the programs of my EQ.9 ...

Finally, to comment here, I wanted to reproduce the wrong format - and changed the language tag back to `de` - rebooted HomeAssistant - and... still, everything is correct.

So it seems to happen during the first init...

**Comment by ekutner** [comment]
@ChristophCaina It should work both ways, I actually never noticed any difference between using only the language code or language-locale.

**Comment by von-Chaps** [comment]
BOSCH OVEN
Cooking.Oven.Program.Cleaning.Ecolysis
Cooking.Oven.Program.HeatingMode.LetRest
Cooking.Oven.Program.HeatingMode.HotAirGentle
Cooking.Oven.Program.HeatingMode.GrillLargeArea

**Comment by ekutner** [comment]
> @ekutner : The reason for what I've noticed in my comment was pretty simple... No translation for the entity available... Therefore, I've created PR #119 it is running locally on my system so far - and working well :)

I saw that but I try to keep the list properly sorted, your PR adds lines which are not sorted. It's not a big deal but I didn't have time to deal with reordering the lines so I didn't merge the PR yet.

**Comment by ChristophCaina** [comment]
Oh okey.
Let me Check how to sort them better

**Comment by ChristophCaina** [comment]
hi @von-Chaps,
Can you maybe provide, how these are displayed in the Homeconnect app?
- Cooking.Oven.Program.Cleaning.Ecolysis => I would use "Eco-Clean" (?)
- Cooking.Oven.Program.HeatingMode.LetRest =>
- Cooking.Oven.Program.HeatingMode.HotAirGentle =>
- Cooking.Oven.Program.HeatingMode.GrillLargeArea => I would use "Grill large area" (?)

hi @DjBac
Can you please provide, how these are displayed in the HomeConnect app?
- Cooking.Hob.Program.PowerLevelMode =>
- Cooking.Hob.EnumType.ZoneSelector.FrontRight =>
Do we also need ZoneSelector "FrontLeft", "RearRight", "RearLeft" - or what ever else is being used?

**Comment by von-Chaps** [comment]
@ChristophCaina 

-     Cooking.Oven.Program.Cleaning.Ecolysis =>Cleaning function
-     Cooking.Oven.Program.HeatingMode.LetRest => Let rest
-     Cooking.Oven.Program.HeatingMode.HotAirGentle => Gentle hot air
-     Cooking.Oven.Program.HeatingMode.GrillLargeArea => Grill, large area

Ecolysis is just displayed as "Cleaning function", it makes no mention in the app of any "eco" aspect.

Many thanks.

**Comment by slippyr4** [comment]
As I understand this, you've taken the design decision to use the full string representation of the various enum types as the state value for the corresponding state entities, and rely on home assistant's translation feature to map from that home connect api defined string to something readable.

This isn't an approach I've seen other integrations use, and I do see that on the surface it's a nice solution, in practice it seems to be more trouble than it's worth. 

The fact that not all parts of HA use the translation system makes a lot of stuff really hard to use. As you acknowledge in the first post, it's not supported in History, which is really unhelpful. It makes creating automations harder, because, for example if you want to do something when the appliance power is turned on, you need to specify a non friendly, overly long string "BSH.Common.EnumType.PowerState.On" instead of just "on", which is typical of all the other integrations I'm familiar with, including the "official" home connect integration.

Are you really wedded to this approach? There's a lot to like about this integration - dynamically only creating relevant entities etc - but the usability regressions compared to the "official" one make it far from clear that this is the best one to use.

**Comment by ekutner** [comment]
That's a good summary and that approach is not going to change for what I believe are good reasons. You are more than welcome to use the other integration.

**Comment by xrh0905** [comment]
BSH.Common.EnumType.AmbientLightColor.Color1 Blue, I guess?

**Comment by d0np3p3** [comment]
Do we have to add the Translation to sensors.*json or select.*.json or both?
I want to correct one and add one Translation.

**Comment by ekutner** [comment]
Both

**Comment by d0np3p3** [comment]
Okay the both diff very much in German, 
Also the order diffs to English, I try to correct the German files, and add the both changes.
I will make a pull request.

**Comment by seb2020** [comment]
Hi,
I have set to use french for the language. I have see that some texte are already translated inside my HA interface but I didn't find the fr.json in the repo. How the translation is done ?

Second question : I have forked the projet to create the fr language file. Sould I translate all the json or only the missing translation ?

**Comment by ekutner** [comment]
@seb2020 Not sure how it can be translated, unless you're using *sensor_value_translation: server* 

It will be great if you do the French translation. Make sure you start with the English file because it is the most complete. Note that the sensor translation is a superset of the select translation, so you don't have to do it twice. Ideally you should translate the whole file so it works as expected for other users.

**Comment by swejmansson** [comment]
Just installed Home Connect Alt through HACS and had issues with translation, tried to switch HA/User language to Swedish, English and British English. Restarted etc, still strange status. Read this post and some others, eventually added to yaml:
`language: en-GB
sensor_value_translation: server`

Now working fine. There is something fishy going on. I will leave it as it is for now. Making this reply to give feedback and help others.

Running:
Home Assistant 2023.3.2
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230306.0 - latest

Home Connect Alt 0.6.0

**Comment by seb2020** [comment]
> @seb2020 Not sure how it can be translated, unless you're using _sensor_value_translation: server_
> 
> It will be great if you do the French translation. Make sure you start with the English file because it is the most complete. Note that the sensor translation is a superset of the select translation, so you don't have to do it twice. Ideally you should translate the whole file so it works as expected for other users.

I will start with the sensor file. Is this possible to test in live my translation ? If I put the file in my HA, item will be renamed with the translation ?

**Comment by ekutner** [comment]
If you place the files in the translations folder and restart HA it should work. Note that you should also translate en.json

**Comment by ekutner** [comment]
@seb2020 you should set the HA UI language to FR, not in the config file

**Comment by metawops** [comment]
After upgrading to 0.6.1 everything related to the translations works _much_ better. 😊 
However, with my Siemens EQ.9 coffee maker I have ONE single sensor still untranslated:

<img width="568" alt="Screenshot 2023-04-09 at 15 50 09" src="https://user-images.githubusercontent.com/376090/230776706-b2e56e26-39f4-4c44-9055-573272eb54ab.png">

The value I currently see is `ConsumerProducts.CoffeeMaker.EnumType.CoffeeMilkRatio.80Percent`  and the name of the entity is `sensor.siemens_ti909701hc_68a40e138d03_consumerproducts_coffeemaker_option_coffeemilkratio`.

Couldn't find anything with `CoffeMilkRatio` in the `en.json` translation file so I thought I might report this here.
I don't know the complete set of possible values here so I'm not able to make a new version of the file (and the German one) for a pull request. 🤷‍♂️

**Comment by metawops** [comment]
Bonus question 😉 
Anyone any idea how to make a Mushroom Select card to show the translated values instead of the original API enums?
Screenshot:

<img width="543" alt="Screenshot 2023-04-09 at 16 19 15" src="https://user-images.githubusercontent.com/376090/230778129-f37b6fc8-ddb2-4285-a9c6-1ba1561e853b.png">

But I guess that's more a question for the Mushroom cards developer, right? 😳

**Comment by EvertJob** [comment]
My dishwasher is showing some strange values:

`Siemens Dishwasher - Active Program` is showing `Dishcare.Dishwasher.Program.Quick45`

**Comment by EddyK69** [comment]
Missing translation on Siemens Washer program:
LaundryCare.Washer.Program.PowerSpeed59 (language Dutch)

**Comment by ekutner** [comment]
@EddyK69 feel free to create a PR with the translation

**Comment by EddyK69** [comment]
> @EddyK69 feel free to create a PR with the translation

See PR #250

**Comment by Langtonpaul** [comment]
Hi all new to scrips and new coffee maker I have a untranslated state for coffee maker.
`ConsumerProducts.CoffeeMaker.Program.Beverage.HotWater` and
`sensor.713050390774001643_consumerproducts_coffeemaker_option_coffeemilkratio`

Can I ask when using Call a service 'Home Connect Alt: Apply setting' on can anyone tell me what the format for both the 'Setting key' and setting value wold be when my entity is.
`select.713050390774001643_consumerproducts_coffeemaker_option_beanamount`
and the state is `ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.Mild`
Thanks

**Comment by ekutner** [comment]
With server translation now supporting the select entities it is finally time to close this issue.
