### ISSUE TITLE
How to add entities to HACSS integration (microwave is missing)

### ISSUE THREAD

**Issue by Allinijhof** [ekutner/home-connect-hass#289]
Hi Ekutner,

Thanks for building the HACSS integration, it is very useful for my dishwasher, steam oven and combi oven. Hence unfortunately the microwave (part of my Siemens combi oven) is not available (no microwave entities available).

How can I enable these missing entities in the HACSS integration so that I am able to control my microwave through home assistant?

Regards,

Allard

In the attached screenshot you will find the Home connect app, the "Verwarmingswijze" = regular oven heating has been enable in the HACSS integration however "Magnetron" = microwave has been missing.

![Screenshot_2023-11-26-12-47-35-09_9f7c1d68ad2a6fad3b248f3ec2a58ba4](https://github.com/ekutner/home-connect-hass/assets/33557920/ad6d0381-05fc-4b6b-a5bb-1d7194b49f63)

**Comment by ekutner** [comment]
Hello, in general all entities are created automatically if they are provided by the API. If you don't see these entities then most likely they are not available in the API. If you want me to take a deeper look you need to follow the issue submission instructions and also add ```log_mode: 7``` to the home_connect_alt section of your configuration.yaml file.

**Comment by TomD011099** [comment]
I'm having similar issues and did some digging.

If you call the API for the available programs of a combi-steam or combi-mircowave device it will only give the `Cooking.Oven.Program.HeatingMode.XXX` options. ([Example response](https://github.com/ekutner/home-connect-hass/files/13490575/programs.json))

The strange thing is, when you select or run the steam or microwave functions, the API accurately represents the running program (`Cooking.Oven.Program.SteamModes.XXX` and `Cooking.Oven.Program.MicroWave.XXX`).

I attached some examples (the microwave is from a different device, but has a similar `/programs` response)

[active-steam.json](https://github.com/ekutner/home-connect-hass/files/13490576/active-steam.json)
[selected-steam.json](https://github.com/ekutner/home-connect-hass/files/13490577/selected-steam.json)
[active-microwave.json](https://github.com/ekutner/home-connect-hass/files/13490578/active-microwave.json)

**Comment by ekutner** [comment]
@TomD011099 Sorry but I don't really follow what you're trying to say. Obviously, the integration can't support what is not available through the API. If the API does show the correct active or selected program then the integration will show that in the relevant sensors regardless of its availability as a settable program.

**Comment by TomD011099** [comment]
@ekutner 
The problem is that it isn't a settable program, but it is readable.

You aren't able to set or read it (it also doesn't show up in the list of available programs where I'm guessing you get the list of programs for each device), but you can see it when the program is actually running on the device.

Eg: A combi microwave oven will only show the oven programs in the programs endpoint and it will only allow these programs to be started remotely. However, when you start a microwave program on the device itself and then check the running program through the API, it will accurately represent the running program with a key that isn't in the available program list. The issue here is that the plugin is only able to read the oven programs (even though the microwave program is sent by the API). This results in an `unknown` value for the program in HA where I'd love to have the `Cooking.Oven.Program.MicroWave.XXX` which is returned by the API

**Comment by ekutner** [comment]
The select box will not show the value if it's not one of the available programs but you should see the correct active program in the Active Program **sensor**.

**Comment by TomD011099** [comment]
Aha, I was trying to use the 'Program selected' condition in my automation. The active program sensor does seem to show the correct value.
Thanks very much for the help!
