### ISSUE TITLE
Request: upon selecting a dishwasher program, have a sensor displaying estimated duration

### ISSUE THREAD

**Issue by pabsi** [ekutner/home-connect-hass#291]
**Is your feature request related to a problem?**
Well, yes and no :sweat_smile: 
The original Home Connect mobile app displays the estimated run time for a program upon selecting it. So when you select Eco, it displays "Duration ~ 225 min", if you change to Auto, it displays "Duration ~ 135 min" and so on. _Before_ starting the programme.

**Describe the solution you'd like**
I'd like to be able to see a sensor that has the estimated run time value same as the mobile app and the original Home Connect integration, upon selecting a program, without starting the dishwasher.

**Describe alternatives you've considered**
I considered creating a helper list for this, since it's only 6 programs (Eco, Auto, Intensive, Pre-Rinse, 1 hour, Machine maintenance). Then upon selecting a program display the matching estimated time for that program from the helper list. But I *think* the API should return this value already?

**Additional context**
I am fairly sure the original Home Connect app has this sensor already.

Thank you so much for your hard work!
PS: I would love to investigate this myself but have 0 idea on how to even start, looking for API return values... :disappointed:

**Comment by ekutner** [comment]
All the sensors are created automatically based on the information provided by the API, so if it is provided and the built-in Home Connect integration shows the information then there would be a sensor for it in this integration as well.

**Comment by pabsi** [comment]
Damn. As much as I'd love to say I have that, I don't. I have `bsh_common_option_startinrelative` which is to delay the start of the program.
I'll see what I can find debugging.
Thanks

**Comment by seidler2547** [comment]
You need to reload the integration while the appliance is running a program. Then the new sensors, e.g. for remaining time, will appear.

**Comment by pabsi** [comment]
I had (and still have) no luck with this. My dishwasher is not reporting the estimated time on the integration. I can't find it on the API responses either. So weird. I swear on the official integration it's present. Also you have an estimated as you said. No idea what can be happening. :(

**Comment by flyingtech** [comment]
I'm wondering the same thing as OP.  There should be something already in the API since the Alexa skill is able to tell me how much time is left on the program. "Alexa, ask My Dishwasher when the dishes will be ready".  this came from the skill page on amazon here: https://www.amazon.com/Home-Connect-GmbH-Dishwasher/dp/B081CSHTJ2/ref=sr_1_1?crid=1P6PCYUMCF0PR&keywords=home+connect+skill&qid=1702351535&sprefix=home+connect+skill%2Caps%2C107&sr=8-1

I'm new to HA and i would be happy to provide my log when the next time the dishwasher is running.

**Comment by flyingtech** [comment]
So i don't know what this means but its definitely in the API based on the logs.  it is sending the remaining time and the percentage of program completion.
"2023-12-11 22:50:16.339 DEBUG (MainThread) [home_connect_async.callback_registery] Broadcasting event: **BSH.Common.Option.RemainingProgramTime = 6480**"

"2023-12-11 22:50:16.339 DEBUG (MainThread) [home_connect_async.callback_registery] Broadcasting event: **BSH.Common.Option.ProgramProgress = 26**"

I couldn't tell you how to use this in home assistant for automation because I'm still learning.

**Comment by pabsi** [comment]
@flyingtech , judging by the name of those, those are for a program which is in progress already, and I already have them:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/108e9d6e-0306-4fa9-8686-a9bbe1cc1cbb)
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/24c2f6b2-8300-405d-b39c-b5c125829248)
(Currently unavailable because I am not running a washing program right now).

What I was asking for was an estimated duration of a program without actually starting it. Which should be displayed based on the selected program from the dropdown:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/afc3f3c4-1733-4053-8b1f-b3ddf0128910)

**Comment by pabsi** [comment]
@ekutner I had some time to double check the original integration. Despite having a "Duration" sensor, it is Unavailable before starting the program. For whatever reason I thought this was available.
So, I intend to do something like a mapping 1:1 of the program -> Estimated duration (like a key->value map). Perhaps we can use this issue as a possible place to investigate if you want. Otherwise, you feel free to close the ticket :+1:

**Comment by ekutner** [comment]
1. I believe the estimated duration is appliance dependent, so whatever you map for your appliance may not be correct for other models.
2. The time will change based on selected options like Echo, Speed, Pre-Wash, etc. 

Bottom line is that it's going to be hard to create a general mapping that would be useful for everyone, especially considering that some appliance, like my washing machine, actually do provide this information in the API. 
Since I'm trying to keep only active issues that I need to track in the "issues" section I'm going to close this one and suggest you use the "Show and Tell" discussion category to share the mapping you do manage to create.

**Comment by pabsi** [comment]
Sounds reasonable. And I agree.
Thank you for all your help, and for the integration :pray: it's still amazing :slightly_smiling_face:

**Comment by pabsi** [comment]
@ekutner I was just doing this mapping thing, and while messing around and enabling debug mode and debug level 7, I saw this in the response upon selecting a program:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/5bbae7d9-7a7c-4069-b2ec-2ced8f9147d4)
However, no sensor is present:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/124c2f54-9e58-4e3e-9aad-5371829298bf)

**Comment by pabsi** [comment]
I feel stupid. This is the exact same sensor as the one that displays the remaining time while running the program. For some reason I was expecting it to be named "estimated" or something. Of course, that's what the other one is for, the "RemainingProgramTimeIsEstimated".... :man_facepalming: 

All I need now, is to display in a more friendly format, as it's rounding up the time:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/eb4c58f1-a950-46fd-9a67-92b62aa7066c)

So instead of "In 4 hours" I need to somehow change that to "In 3 hours 35 minutes" or whatever...

**Comment by ekutner** [comment]
The rounded time display is done by HA for some reason. You can create a custom sensor and use a template like this convert the seconds into something more user friendly:
```     
       {% set timediff =
		as_datetime(states("sensor.bosch_wat286h0gb_68a40e3587eb_bsh_common_option_remainingprogramtime"))-now() 
		%} {{ timediff.seconds//3600 }}:{{
		'{:02d}'.format((timediff.seconds-(timediff.seconds//3600)*3600)//60) }}h
```

**Comment by pabsi** [comment]
Amazing! With that little snippet I was able to do this as a helper template:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/575b9b03-71db-44b3-b634-3702e032856d)

And got exactly what I wanted:
![image](https://github.com/ekutner/home-connect-hass/assets/5247611/18abb36f-56da-4cb2-a2e3-ae472f6bbaba)

The seconds are probably a bit much, but hey, it's perfect!

Thank you so much @ekutner :pray:
