### ISSUE TITLE
Error 500 when configuring via UI

### ISSUE THREAD

**Issue by Phoenix-DH** [ekutner/home-connect-hass#340]
Hey,

I just updated to version 1.1.0 and had to remove my infos from secrets.yaml to get the integration back working.
Afterwards I tried to check the UI config again, but then I get this:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I have HA 2024.2.2 and as mentioned version 1.1.0 from the integration.

**Comment by bkbartk** [comment]
I think I have the same error
![image](https://github.com/ekutner/home-connect-hass/assets/17070805/616ac68a-625d-4825-8ca1-1f31b24108da)

**Comment by bkbartk** [comment]
and I also found the solution
you need to remove the 
`home_connect_alt` section from configuration.yaml and then restart.
it's not needed, but for somehow still read and complains about invalid options `client_id` and `client_secret`.

somewhere during my checks I removed the complete integration, so I'm not sure but I don't think this is needed.
if not all your devices are found you need to turn them on. Only my dishwasher was found at first because it was running. My laundry machine, I needed to turn on.

**Comment by Slychocobo** [comment]
Seem to be getting the same error, however removing the home_connect_alt section from the configuration has not helped.

Removing the configuration and trying to re-add it has not helped either, instead I simply get the same 500 Internal server error during the Oauth registration process

**Comment by Phoenix-DH** [comment]
When removing the config, everything is working, no errors in the log, also all devices are discovered.

There is only the error when trying to open the configuration from ui.

**Comment by Krocko** [comment]
Same problem here.

**Comment by mdkeil** [comment]
> There is only the error when trying to open the configuration from ui.
+1

**Comment by Robbe-B** [comment]
+1

**Comment by sabbatho** [comment]
+1

**Comment by Jurrjuna** [comment]
Same issue here. 

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by SkyTest-123** [comment]
+1. Same.

**Comment by ekutner** [comment]
10 people and not a single log...
Please attach a debug log.

**Comment by ekutner** [comment]
Please update to 1.1.1, it should fix that issue

**Comment by sabbatho** [comment]
Sorry for not attaching logs, should have done that obviously.

1.1.1 confirmed working for me!

**Comment by Phoenix-DH** [comment]
Yes back working! Thanks.
