### ISSUE TITLE
Authentication feedback not working

### ISSUE THREAD

**Issue by AleXSR700** [ekutner/home-connect-hass#36]
Hello,
I would like to reopen the unautorized_client issue.  Maybe it is due to a breaking change but I cannot use the oauth since my setup is local only.

I have My Home Assistant and my setup is not reachable via external url.
So I need to use
`http://192.168.0.2:8123/auth/external/callback `
instead of
`https://my.home-assistant.io/redirect/oauth`

When I make the change manually in the error screen
`"error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",`
then I am routed to home connect and can approve the access. But then I am returned to HA and I just see "error" in the integration screen.

P.S.: Log is empty despite logger set to debug

**Comment by ekutner** [comment]
Make sure you follow the Home Connect app configuration instructions. You need to set up the correct redirect URL in the Home Connect app.

**Comment by AleXSR700** [comment]
It is configured correctly as http://192.168.0.2:8123/auth/external/callback

It works with the home connect integration which is running right now.

It is not working with your integration.

Your integration calls a different link. I manually change the link as explained using the above callback (which is set as sich in my applications.

**Comment by ekutner** [comment]
the error says "client or redirection URI not authorized", since you got passed the login screen to HC it is probably the redirect URL. The integration is using the standard OAuth mechanism provided by HA, so the URL is the same as the one used by the built-in integration. Try removing and adding back the built-in integration and see if that still works, if you're using the same HC app then I assume it won't.
When you get the error try looking at the URL on your browser, there might be a query string param there that shows the expected redirect URL that you need to configure. It should have the same domain as the one you are using to access your HA instance.

**Comment by AleXSR700** [comment]
`client or redirection URI not authorized`
No, that is the first error when I hit the authenticate button in the UI of your integration.
This is cause by your integration using the default link.
When I change that default link to the adjusted one (IP+callback) the error is fixed/bypassed and I get to home connect dev webpage. 
There I can authorize the app correctly but the feedback to your integration then fails. Your integration UI screen only says "error" without any information nor log entries.

So I can authorize on hc dev website after adjusting the url your integration creates but the feedback of success does not seem to reach the integration correctly.

As I said, no proper error message or leg entries supplied so I can only report the steps.

**Comment by ekutner** [comment]
Again, the Oauth flow is managed by HA directly and it generates the redirect URL, not the integration. There would be no log if HA never gets the callback after the login flow completes, and even if it did complete you would have to set the general HA log level to debug, not the integration's log level. 
I don't know what you mean by "default link" but the domain part you are configure in HC needs to match the domain you are using to access HA. 
As noted before, I suggest you try removing and adding back the built-in integration to see if that flow works there.

**Comment by emufan** [comment]
But if HA changed something (perhaps something around the oauth), what you have perhaps to adapt, is it the right idea to close each issue and only point to HA? I'm currently not able to re-add your integration, either. Some behavior as the others are describing.

**Comment by ekutner** [comment]
It seems to be working fine for most people. There were some who reported issues and then realized it is caused by an app configuration problem. As of now I have to information that suggests this might be a problem with the integration, that is why I closed the issue. 
I'm not sure I understand what you mean when you say you can't re-add it.

**Comment by emufan** [comment]
I was able to add it in my test instance. But was not able to add it in my pro instance. Of course I added a new application, etc.

What was possible before: Use callback links like http://192.168.0.2:8123/auth/external/callback

Currently (at least here) this is not possible anymore. Because the oauth call is hard coded using https://my.home-assistant.io/redirect/oauth. And even if I changed this in the url to the local one above (and enabled in BSH integration) it only throwed "error".

Now it only worked with https://my.home-assistant.io/redirect/oauth as redirect url set up in the application and with my.home-assistant.io set up in the browser. I have never used one of them before.

So, yes, problem closed here now, but I had to do it completely other than before. Perhaps you can add this as hints in the readme.

**Comment by AleXSR700** [comment]
So you can confirm that the IP callback approach no longer works?
Since this is the only supported way of doing it on some systems (like mine), the integration will not be able to authorize or more precisely, not be able to know that I authorized it since the feedback is the part that seems to not be working anymore.
