### ISSUE TITLE
High CPU Load

### ISSUE THREAD

**Issue by henfri** [ekutner/home-connect-hass#384]
## Version of the custom_component
1.1.6

## Configuration
all default

## Debug log
I have created a profile with the profiler addon of home assistant. I can provide that

This integration - and also the official one , which I checked as a reference - use almost 50% of the CPU time of HomeAssistant and the CPU load of the System increases quite a bit when activating it
![chrome_C6MJz6edL1](https://github.com/ekutner/home-connect-hass/assets/5280909/b254a380-0660-463e-9f42-bfa912054559)

This seems not justified and it would be great if you could check if this can be improved.

Greetings,
Hendrik

**Comment by ekutner** [comment]
The screenshot refers to the built-in HC integration and in there to sseclient, which is a python library that supports SSE. I'm using the same library but on my machine I only see about 10% CPU usage in total, so didn't even try to profile. 
If you're still having this issue please uninstall the built in integration and upload a clean profile log file. Also upload a screenshot of CPU usage from the Settings->System->Hardware screen in HA. That said, considering that library has not been updated since 2020 I doubt there will be anything I can do about it.
