### ISSUE TITLE
Weird states?

### ISSUE THREAD

**Issue by christianreiss** [ekutner/home-connect-hass#411]
## Describe the bug

The states of operations states seem to be weird in 1.1.7 is weird. 
I did a fresh installation (removed all Home Connect and Home Connect Alt integrations and restarted HA).

For example the Dishwasher operation state has to be like this:
```
      - condition: state
        entity_id: sensor.011030518998005596_bsh_common_status_operationstate
        state: BSH.Common.EnumType.OperationState.Ready
```

I would prefer it to be like
```
      - condition: state
        entity_id: sensor.011030518998005596_bsh_common_status_operationstate
        state: Ready
```

The Logbook does report the states correctly "Run", "Ready" etc. The States in the Developer Tools are as above.

2nd issue: I renamed the Dishwasher to Dishwasher but it's preppended by "Bosch". Its okay I fixed and renamed all my autiomations and Dashboards, but this is weird.

Note: I came from non-alt to alt version. The alt version is way better than the non-alt.

Thanks!

**Comment by christian1986** [comment]
I see the same behavior. Ideas?

**Comment by ekutner** [comment]
This has always been the behavior, it's not new in 1.1.17. It's a matter of taste but I strongly believe that code should not be language dependent so the states of the entities as ENUM values coming from the API and the display value is a translation. If you change the translation mode to "Server" n the integration's options it should give you translated states instead of the ENUM.
