### ISSUE TITLE
too long names

### ISSUE THREAD

**Issue by pswid** [ekutner/home-connect-hass#47]
Currently, entity names ("friendly names") consist of manufacturer name + device name (given by the user in the mobile app) + parameter name. As a result, such names are not fully visible at dashboard, so each of them has to be "manually" changed (shortened). Why not to leave only the parameter names (as it is in the official integration)? It would help a lot.

change from this:

![image](https://user-images.githubusercontent.com/78219494/172834278-18e0c89a-cff5-459d-99ca-f849ad98b675.png)

to this:

![image](https://user-images.githubusercontent.com/78219494/172834383-0e3c7d57-546f-449b-8446-26d81dc6587f.png)

**Comment by emufan** [comment]
This would work automatically (in device dashboard), if the names would lose their " - ".

Currently: Geschirrspüler - Betriebsstatus. Displayed as Geschirrspüler - Betriebsstatus.
If it would be Geschirrspüler Betriebsstatus, it would be displayed as Betriebsstatus, because Lovelace is removing 1:1 prefixes in this case if same as Device.

Would be an improvement for Device-Dashboard.

But to remove the device name completely, I would not like to have this. Because if you have more devices ...

For custom dashboard, the user is still able to rename as he want.

**Comment by ekutner** [comment]
I general this didn't bother me and doesn't seem to bother most other users.
I agree with @emufan that removing the appliance name completely is a bad idea because different appliances would have the same entity display names.
I see few options how to handle it:
1. Leave as is.
2. Remove the band name but leave the appliance name. So instead of "Bosch Washing machine" it will be just "Washing machine".
3. Move the appliance name to the end, so it becomes something like "Program Progress (Washing machine)".

I'm going to leave this issue open for a while to collect feedback from other users as I don't have a strong opinion on it.

**Comment by emufan** [comment]
With option 3, the build in prefix removal in device view is not working anymore. So I would skip this. Personally I don't care much, because I already renamed it and removed the " - " ans some names, which are more convenient for me that BSH created. And most of the users would do so.

But if I would start from scratch I would prefer

4. your proposal 2. but without " - ".

**Comment by pswid** [comment]
The best solution would be to add an option in the configuration, so that each user could choose the variant that suits him the best.
I prefer to leave only option names. Because even if the user has several devices with the same options, it is still easy to find out which of them a specific entity belongs to (e.g. by looking at the entity id). Besides, on dashboards, options for each device are usually grouped in one card, so the name of the device can displayed e.g. as a card's title and there is no point in repeating it with all options. Don't you think? Renaming all entities it's a lot of unnecessary work in such cases, especially if someone owns many HomeConnect devices (I own 9 devices).

**Comment by Mitch73-2** [comment]
The option Pswid suggests above is the best option in my opinion.

**Comment by ekutner** [comment]
I agree this is a good idea. It was added to the latest beta and will be made GA when the beta is merged into the main branch.

**Comment by pswid** [comment]
Is this functionality already available in [v0.5.0-b5](https://github.com/ekutner/home-connect-hass/releases/tag/v0.5.0-b5)? if so, how to use it?

**Comment by haimn** [comment]
> Is this functionality already available in [v0.5.0-b5](https://github.com/ekutner/home-connect-hass/releases/tag/v0.5.0-b5)? if so, how to use it?

You can see how to use it in the README:
https://github.com/ekutner/home-connect-hass#configuration-options
Use "name_template" configuration.

**Comment by michalk-k** [comment]
How to enforce regenerating names of entities after changing the template?
