### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by labaland** [ekutner/home-connect-hass#55]
Hi, i have a BOSCH dishwasher.
Is it possible to change "select" to a switch to power on & off?

 select.010100522145000977_bsh_common_setting_powerstate

**Comment by GHeiner** [comment]
Hi I support this request.

**Comment by ekutner** [comment]
As a general rule the UI control to use is automatically detected based on the type of the entity in the HC API. A switch control is used for boolean entities, however the power state entity is not boolean (and in fact it has other states than on/off). All that said I think it does make sense to show a switch for appliances where the entity has exactly two states which happen to be on/off, so I've make that change and you can try it out with beta version 0.5.0-b8. 
Note that this wasn't a trivial change so let me know how it works.

**Comment by labaland** [comment]
> As a general rule the UI control to use is automatically detected based on the type of the entity in the HC API. A switch control is used for boolean entities, however the power state entity is not boolean (and in fact it has other states than on/off). All that said I think it does make sense to show a switch for appliances where the entity has exactly two states which happen to be on/off, so I've make that change and you can try it out with beta version 0.5.0-b8. Note that this wasn't a trivial change so let me know how it works.

Sweet!

And one more request:
is it possible for u or us? to change the state from "Dishcare.Dishwasher.Program.MachineCare" to "MachineCare" or / "Machine Care"

![image](https://user-images.githubusercontent.com/20958435/174444352-deebbb6e-40f3-4c5c-9eba-cc1139e5689b.png)

It is showing right here but not when using state templates with like custom:button-card:

![image](https://user-images.githubusercontent.com/20958435/174444449-d2071675-a88a-4348-aee8-837e31323b33.png)

**Comment by ekutner** [comment]
Enum values in history can't be translated, if you're seeing them in current values then please submit a PR with updates to the translation files. See #26 for more info.

**Comment by pswid** [comment]
It works for some of the devices, but not all:
- coffee machine also has two power states but instead **On** and **Off** it has **On** `BSH.Common.EnumType.PowerState.On` and **Standby** `BSH.Common.EnumType.PowerState.Standby`. 
- washing machine and dryer has also two states but **On** `BSH.Common.EnumType.PowerState.On` and "**Totally off"** (probably `BSH.Common.EnumType.PowerState.MainsOff`). Unfortunately if you remotely trigger state "totally off" washing machine or dryer powers off totally (so also disconnects from the cloud) and you can power it on again only locally. So maybe instead of **on/off** switch the better option would be just **off** button?

**Comment by pswid** [comment]
It does, but for the devices mentioned above, PowerStatus, although only two values are possible, is still displayed as `select` and not `switch`. **Standby** (and **MainsOff**?) should be equivalent to **Off**. Don't you think?

![image](https://user-images.githubusercontent.com/78219494/174604199-8d01eb60-6e89-4565-baf5-20a880161a29.png)

**Comment by pswid** [comment]
I also noticed that for ovens integration shows PowerStatus as `select `with 4 options (`on`, `off`, `mainsoff` and `standby`) while only two of them are working (`on` and `standby`). The other two (`off` and `mainsoff`) cause 409 error.

I don't know why the HC API reports four available PowerState options for ovens, while the documentation  https://api-docs.home-connect.com/settings#power-state  mentions only about two of them (it's probably an API bug). So in the case of ovens, you could also make a `switch` (`on` and `standby` values) instead of `select` with options that are not working...

**Comment by GHeiner** [comment]
Hi i tested the new power switch with my dishwasher and it worked excellent. I only have a Bosch Bosch dishwasher so I couldn't test more. 

But fif you want me to test something please let me know.

**Comment by ekutner** [comment]
There is nothing special about the power setting either. I added generic handling of enums that only have On/Off values but I don't want to second guess what the other values do.
