### ISSUE TITLE
Energy consumption info?

### ISSUE THREAD

**Issue by uspino2** [ekutner/home-connect-hass#90]
My appliances are supposed to provide energy consumption information at the end of a cycle or when turned off. It's in the instructions and the menu, but I've never been able to get that info. Is that something that can be read by this plugin and (hopefully) integrated into the HA Energy Dashboard? Thanks.

**Comment by ekutner** [comment]
If it was available you would have already seen it. The integration automatically loads and displays all the information made available by the API.

**Comment by EvertJob** [comment]
Have a look at athom.tech. The made affordable devices to measure the energy consumption.

**Comment by mark007** [comment]
I know this is closed but I was also hoping to use the integration so that I could show the power/energy usage of my Bosch dishwasher on the HA energy dashboard.

I do see an entity get created when a wash is on, ending in 'energyforecast'. I can't find details anywhere on this, is it the watts that the device is using or something along those lines?

If so, is it within the integrations control to make an actual energy sensor that would be compatible with the HA energy dashboard. The current energy forecast sensor doesn't seem to be addable to the HA energy dashboard as it stands.

**Comment by Meatballs1** [comment]
I think the energyforecast  is a % for the bar charts show in the application. 

Some of the downloadable programs show their energy use on the download page, but I cant see usage for pre-existing programs. You should be able to find Eco mode on the technical data sheets e.g. : https://media3.neff-international.com/Documents/eudatasheet/en-GB/S189YCX02E.pdf

Mixed Load 1.2kWh
Quick Wash 0.7kWh
Quick Wash and Dry 1.0kWh
Super 60 1.4kWh

Could potentially extrapolate the kWh usage from one of those so my Eco mode has 30 in the forecast so each % is 0.0215kWh...

**Comment by Meatballs1** [comment]
Super 60 shows as 60% so 0.023 kWh per %
Mixed Load as 54% = 0.022kWh 

Adding in all the extra power modes made Super 60 72% so I would estimate at 1.6kWh etc
